# Generated by Django 4.2.26 on 2025-11-26 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='saints/')),
                ('category', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('born_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('born_date_text', models.CharField(blank=True, max_length=100, null=True)),
                ('death_date_text', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=150, null=True)),
                ('death_place', models.CharField(blank=True, max_length=150, null=True)),
                ('feast_day', models.DateField(blank=True, null=True)),
                ('canonization_date', models.DateField(blank=True, null=True)),
                ('canonization_date_text', models.CharField(blank=True, max_length=100, null=True)),
                ('patronages', models.TextField(blank=True, null=True)),
                ('quotes', models.TextField(blank=True, null=True)),
                ('sources', models.TextField(blank=True, null=True)),
                ('title_pt', models.CharField(max_length=100)),
                ('content_pt', models.TextField()),
                ('description_pt', models.TextField()),
                ('category_pt', models.CharField(max_length=100)),
                ('country_pt', models.CharField(max_length=100)),
                ('born_date_text_pt', models.CharField(blank=True, max_length=100, null=True)),
                ('death_date_text_pt', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_place_pt', models.CharField(blank=True, max_length=150, null=True)),
                ('death_place_pt', models.CharField(blank=True, max_length=150, null=True)),
                ('canonization_date_text_pt', models.CharField(blank=True, max_length=100, null=True)),
                ('patronages_pt', models.TextField(blank=True, null=True)),
                ('quotes_pt', models.TextField(blank=True, null=True)),
                ('sources_pt', models.TextField(blank=True, null=True)),
                ('title_en', models.CharField(max_length=100)),
                ('content_en', models.TextField()),
                ('description_en', models.TextField()),
                ('category_en', models.CharField(max_length=100)),
                ('country_en', models.CharField(max_length=100)),
                ('born_date_text_en', models.CharField(blank=True, max_length=100, null=True)),
                ('death_date_text_en', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_place_en', models.CharField(blank=True, max_length=150, null=True)),
                ('death_place_en', models.CharField(blank=True, max_length=150, null=True)),
                ('canonization_date_text_en', models.CharField(blank=True, max_length=100, null=True)),
                ('patronages_en', models.TextField(blank=True, null=True)),
                ('quotes_en', models.TextField(blank=True, null=True)),
                ('sources_en', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('title_pt', models.CharField(max_length=200)),
                ('content_pt', models.TextField()),
                ('category_pt', models.CharField(blank=True, max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200)),
                ('content_en', models.TextField()),
                ('category_en', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prayers', to='articles.article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='patron_of',
            field=models.ManyToManyField(blank=True, related_name='patrons', to='articles.city'),
        ),
    ]
