# Generated by Django 4.2.26 on 2025-12-10 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('name_pt', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('abbreviation', models.CharField(max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='articles.country')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='patron_of_country',
            field=models.ManyToManyField(blank=True, related_name='patrons_countries', to='articles.country'),
        ),
        migrations.AddField(
            model_name='article',
            name='patron_of_state',
            field=models.ManyToManyField(blank=True, related_name='patrons_states', to='articles.state'),
        ),
    ]
