# Generated by Django 4.2.26 on 2025-12-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_country_alter_article_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='patron_of_country',
        ),
        migrations.RemoveField(
            model_name='article',
            name='patron_of_state',
        ),
        migrations.AddField(
            model_name='country',
            name='patron_saints',
            field=models.ManyToManyField(blank=True, related_name='patrons_of_country', to='articles.article'),
        ),
        migrations.AddField(
            model_name='state',
            name='patron_saints',
            field=models.ManyToManyField(blank=True, related_name='patrons_of_state', to='articles.article'),
        ),
    ]
