# Generated by Django 4.2.26 on 2025-12-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_patron_of_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country_en',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
