# Generated by Django 6.0 on 2025-12-24 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_city_country_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='birth_place',
        ),
        migrations.RemoveField(
            model_name='article',
            name='born_date_text',
        ),
        migrations.RemoveField(
            model_name='article',
            name='canonization_date_text',
        ),
        migrations.RemoveField(
            model_name='article',
            name='death_date_text',
        ),
        migrations.RemoveField(
            model_name='article',
            name='death_place',
        ),
    ]
