# Generated by Django 6.0 on 2025-12-24 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_article_birth_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='country',
        ),
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='patronages',
        ),
        migrations.RemoveField(
            model_name='article',
            name='quotes',
        ),
        migrations.RemoveField(
            model_name='article',
            name='sources',
        ),
    ]
