# Generated by Django 6.0 on 2025-12-24 20:59

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_remove_article_category_remove_article_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prayer',
            name='category',
        ),
        migrations.RemoveField(
            model_name='prayer',
            name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='search_vector_en',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='search_vector_pt',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='prayer',
            name='search_vector_en',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='prayer',
            name='search_vector_pt',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='birth_place_en',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='birth_place_pt',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='born_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='born_date_text_en',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='born_date_text_pt',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='canonization_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='canonization_date_text_en',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='canonization_date_text_pt',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='category_en',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='category_pt',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='country_en',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='country_pt',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='death_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='death_date_text_en',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='death_date_text_pt',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='death_place_en',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='death_place_pt',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='description_en',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='description_pt',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='feast_day',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, db_index=True, null=True, upload_to='saints/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='patron_of',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='patrons', to='articles.city'),
        ),
        migrations.AlterField(
            model_name='article',
            name='patronages_en',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='patronages_pt',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='sources_en',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='sources_pt',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_en',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_pt',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='city',
            name='country_en',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_en',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_pt',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='country',
            name='patron_saints',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='patrons_of_country', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='category_en',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='category_pt',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='title_en',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='title_pt',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='state',
            name='abbreviation',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='state',
            name='patron_saints',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='patrons_of_state', to='articles.article'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector_pt'], name='articles_ar_search__b5ee6f_gin'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector_en'], name='articles_ar_search__96845d_gin'),
        ),
        migrations.AddIndex(
            model_name='prayer',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector_pt'], name='articles_pr_search__759064_gin'),
        ),
        migrations.AddIndex(
            model_name='prayer',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector_en'], name='articles_pr_search__d35cc3_gin'),
        ),
    ]
