# Generated by Django 6.0 on 2026-01-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='country_en',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='country_pt',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
